/*
 Navicat Premium Data Transfer

 Source Server         : local
 Source Server Type    : PostgreSQL
 Source Server Version : 120003
 Source Host           : localhost:5432
 Source Catalog        : aiyun_cloud
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120003
 File Encoding         : 65001

 Date: 19/05/2022 18:26:00
*/


-- ----------------------------
-- Sequence structure for lpm_sys_admin_copy1_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."lpm_sys_admin_copy1_id_seq";
CREATE SEQUENCE "public"."lpm_sys_admin_copy1_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for lpm_sys_admin_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."lpm_sys_admin_id_seq";
CREATE SEQUENCE "public"."lpm_sys_admin_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for lpm_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."lpm_user_id_seq";
CREATE SEQUENCE "public"."lpm_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for lpm_sys_admin
-- ----------------------------
DROP TABLE IF EXISTS "public"."lpm_sys_admin";
CREATE TABLE "public"."lpm_sys_admin" (
  "id" int4 NOT NULL GENERATED ALWAYS AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "role_id" int2,
  "username" varchar(20) COLLATE "pg_catalog"."default",
  "password" varchar(50) COLLATE "pg_catalog"."default",
  "salt" varchar(5) COLLATE "pg_catalog"."default",
  "email" varchar(50) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "avatar" varchar(150) COLLATE "pg_catalog"."default",
  "create_at" timestamptz(6),
  "update_at" timestamptz(6),
  "status" int2 DEFAULT 1
)
;

-- ----------------------------
-- Records of lpm_sys_admin
-- ----------------------------
INSERT INTO "public"."lpm_sys_admin" OVERRIDING SYSTEM VALUE VALUES (8, 1, 'admin', '315193380d2fedffa677b7fe236fadb5', 'sinb', NULL, NULL, NULL, '2022-05-19 16:25:34+08', '2022-05-19 16:25:36+08', 1);

-- ----------------------------
-- Table structure for lpm_sys_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."lpm_sys_role";
CREATE TABLE "public"."lpm_sys_role" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of lpm_sys_role
-- ----------------------------
INSERT INTO "public"."lpm_sys_role" VALUES (4, '1');
INSERT INTO "public"."lpm_sys_role" VALUES (5, '2');
INSERT INTO "public"."lpm_sys_role" VALUES (6, '123');
INSERT INTO "public"."lpm_sys_role" VALUES (7, '1231');
INSERT INTO "public"."lpm_sys_role" VALUES (8, '21321');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."lpm_sys_admin_copy1_id_seq"
OWNED BY "public"."lpm_sys_role"."id";
SELECT setval('"public"."lpm_sys_admin_copy1_id_seq"', 8, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."lpm_sys_admin_id_seq"
OWNED BY "public"."lpm_sys_admin"."id";
SELECT setval('"public"."lpm_sys_admin_id_seq"', 8, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."lpm_user_id_seq"', 3, true);

-- ----------------------------
-- Auto increment value for lpm_sys_admin
-- ----------------------------
SELECT setval('"public"."lpm_sys_admin_id_seq"', 8, true);

-- ----------------------------
-- Primary Key structure for table lpm_sys_admin
-- ----------------------------
ALTER TABLE "public"."lpm_sys_admin" ADD CONSTRAINT "lpm_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for lpm_sys_role
-- ----------------------------
SELECT setval('"public"."lpm_sys_admin_copy1_id_seq"', 8, true);

-- ----------------------------
-- Primary Key structure for table lpm_sys_role
-- ----------------------------
ALTER TABLE "public"."lpm_sys_role" ADD CONSTRAINT "lpm_sys_admin_copy1_pkey" PRIMARY KEY ("id");
